version: '3.7'

services:

  web:
    stdin_open: true
    tty: true
    container_name: test-actions
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '.:/usr/src/app'
    ports:
      - 3000:3000
    command: yarn start
