on:
  push:
    branches:
      - master

name: Deploy to Digitalocean

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kenessajr/test-actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-prod

    - name: Deploy image to digitalocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        port: ${{ secrets.DO_PORT }}
        script: docker run -t -p 80:80 kenessajr/test-actions:latest
    
